package com.sample;

global QuestionCommunicator questionCommunicator;
global DiagnosisMaster diagnosis;

import org.drools.marshalling.impl.ProtobufMessages

rule "Init"
    when
    then
        System.out.println("Initializiing...");
        boolean age = questionCommunicator.createQuestion("Are you over 18 sweetheart?");
		String sex =  questionCommunicator.createSelectOptionQuestion("What's your gender?", new String[] {"male", "female", "devil knows"});
		diagnosis.setSex(sex);
		diagnosis.setOverEighteeen(age);
        String[] compoundAnswer = questionCommunicator.createSelectOptionsQuestion("Co Cię boli, czy aż tak to cię boli, czy Rychu peja ma dziś szansę uczciwie zarobić?", new String[] {"klatka", "brzuch"});
		for(String ans : compoundAnswer) {	
			insert(ans);
		}
		insert(diagnosis);
end
rule "Chest"
	when s: String(s == "klatka")
	then
		diagnosis.setChestPain(true);
		System.out.println(diagnosis.isChestPain());
		update(diagnosis);
end

rule "Stomach"
	when s: String(s == "brzuch")
	then
		diagnosis.setStomachPain(true);
		update(diagnosis);
end

rule "Stuffiness"
    when d : DiagnosisMaster(d.isChestPain() == Question.TRUE)
    then
    	//System.out.println(d.isStuffiness());
        d.setStuffiness(questionCommunicator.createQuestion("Czy masz uczucie duszności?"));
        System.out.println(d.isStuffiness());
        update(d);
    end

rule "NoStuffiness"
    when d : DiagnosisMaster(d.isStuffiness() == Question.FALSE)
    then
        diagnosis.setChestPain(false);
        update(d);
    end


rule "StuffinessAfterSports"
    when d : DiagnosisMaster(d.isStuffiness() == Question.TRUE)
    then
        d.setSportStuffiness(questionCommunicator.createQuestion("Czy uczucie duszności nasila się przy wysiłku fizycznym?"));
        update(d);
    end 


